exclude: [
  './inc/scss/framework/*.*'
]

linters:
  BorderZero:
    convention: none
  DeclarationOrder:
    enabled: false
  Indentation:
    enabled: true
    character: space
    width: 4
  PropertySortOrder:
    enabled: false
    order:
      - content
      -
      - width
      - max-width
      - height
      - max-height
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-radius
      - box-sizing
      - display
      - vertical-align
      - float
      -
      - position
      - top
      - right
      - bottom
      - left
      - overflow
      -
      - font-family
      - font-size
      - font-weight
      - font-style
      - line-height
      - text-align
      - text-transform
      - text-decoration
      - letter-spacing
      - color
      -
      - background-color
      - background-image
      - background-repeat
      - background-size
      - background-position
      - background-attachment
    separate_group: true
  PropertySpelling:
    enabled: true
    extra_properties: [
      '*display',
      '*height',
      '*padding-bottom',
      '*padding-top',
      '*vertical-align',
      '*zoom'
    ]
  SelectorFormat:
    convention: 'hyphenated_BEM'
  VendorPrefix:
    identifier_list: 'bourbon'